import { SiteSettings, Project, ServiceItem, MaterialItem, GalleryItem, ReviewItem } from '../types';

export const DEFAULT_SITE_SETTINGS: SiteSettings = {
  companyName: 'JM INTERIOR',
  tagline: 'Crafting Timeless Living Spaces & Custom Woodwork',
  description: 'Premium interior design studio and custom woodwork specialists based in Chennai, led by Master Craftsman K. Selvam.',
  logoUrl: '',
  ownerName: 'K. Selvam',
  experienceYears: '18+',
  phone: '+91 74012 79764',
  whatsapp: '+917401279764',
  email: 'selvam@jminterior.in',
  address: 'No. 24, Gandhi Road, Velachery, Chennai, Tamil Nadu - 600042',
  heroTitle: 'Bespoke Interior Design & Architectural Woodwork',
  heroSubtitle: 'Transforming luxury residences and modern commercial spaces across Chennai with artisanal woodworking, refined spatial layouts, and uncompromising attention to detail.',
  heroImage: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1920&q=80',
  heroCtaPrimary: 'Explore Projects',
  heroCtaSecondary: 'Book Consultation',
  aboutTitle: 'Mastery in Woodwork, Excellence in Interior Design',
  aboutDescription: 'Founded and directed by K. Selvam, JM INTERIOR brings nearly two decades of hands-on mastery to luxury homes, modular kitchens, living halls, and commercial interiors in Chennai. We believe every space should reflect its inhabitant with warmth, structural elegance, and enduring materials.',
  designPhilosophy: 'We merge traditional carpentry wisdom with state-of-the-art interior ergonomics. Every cut, joinery, veneer, and finish is thoughtfully calibrated for longevity and aesthetic peace.',
  socialInstagram: 'https://instagram.com',
  socialFacebook: 'https://facebook.com',
  socialYouTube: 'https://youtube.com',
  footerText: 'Dedicated to artisanal excellence and high-end residential interiors in Chennai, Tamil Nadu.',
  appointmentNotice: 'Consultations are scheduled in advance. Site visits within Chennai can be arranged upon inquiry.',
  updatedAt: new Date().toISOString(),
};

export const INITIAL_SERVICES: Omit<ServiceItem, 'id'>[] = [
  {
    title: 'Modular Kitchens & Pantries',
    description: 'Bespoke kitchen configurations engineered with marine-grade boiling waterproof plywood, premium acrylic finishes, and soft-close ergonomic hardware.',
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80',
    features: ['BWP Grade Ply', 'Quartz & Granite Countertops', 'Hafele/Blum Hardware', 'Custom Cutlery Trays'],
    startingPrice: '₹1.8 Lakhs',
    order: 1,
    isPublished: true,
  },
  {
    title: 'Living Hall & Entertainment Lounges',
    description: 'Grand TV wall panels, fluted acoustic wooden partitions, custom false ceilings with warm cove illumination, and bespoke display vitrines.',
    imageUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80',
    features: ['Veneer & Charcoal Louvers', 'Integrated Ambient Lighting', 'Concealed Cable Routing', 'Designer Bookshelves'],
    startingPrice: '₹1.5 Lakhs',
    order: 2,
    isPublished: true,
  },
  {
    title: 'Luxury Bedroom & Walk-in Wardrobes',
    description: 'Floor-to-ceiling floor wardrobes with tinted glass profiles, cushioned headboard paneling, and acoustic panelling for restful sanctuaries.',
    imageUrl: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=800&q=80',
    features: ['Profile Glass Shutter Wardrobes', 'Cushioned Velvet Bed Backs', 'Smart Sensor Wardrobe Lights', 'Bespoke Dressing Units'],
    startingPrice: '₹2.0 Lakhs',
    order: 3,
    isPublished: true,
  },
  {
    title: 'Bespoke Custom Woodwork & Furniture',
    description: 'Handcrafted solid teakwood dining tables, prayer units (Pooja Mandapams) carved with precision, and custom accent furniture.',
    imageUrl: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=800&q=80',
    features: ['First Quality Teak Wood', 'Traditional Joinery Techniques', 'Hand-rubbed PU Polish', 'Custom Brass Accents'],
    startingPrice: '₹75,000',
    order: 4,
    isPublished: true,
  },
  {
    title: 'Commercial & Executive Offices',
    description: 'Sophisticated meeting rooms, executive veneer desk suites, reception counters, and ergonomic modular office partitions.',
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    features: ['Acoustic Wall Paneling', 'Executive Conference Tables', 'Reception Desks with Backlit Signage', 'Storage Credenzas'],
    startingPrice: '₹3.0 Lakhs',
    order: 5,
    isPublished: true,
  },
];

export const INITIAL_MATERIALS: Omit<MaterialItem, 'id'>[] = [
  {
    name: 'Boiling Water Proof (BWP) Marine Ply',
    description: '710 grade calibrated marine plywood engineered to resist moisture, termites, and warping, ideal for kitchens and vanity units.',
    properties: 'Phenolic bonded, waterproof, termite & borer proof',
    durability: '25+ Years Life Expectancy',
    finish: 'Calibrated core for seamless laminate/veneer pressing',
    usage: 'Kitchen cabinets, bathroom vanities, external wet areas',
    imageUrl: 'https://images.unsplash.com/photo-1546484396-fb3fc6f95f98?auto=format&fit=crop&w=600&q=80',
    isPublished: true,
  },
  {
    name: 'Natural Natural Wood Veneers',
    description: 'Sustainably sourced fine timber leaves including Teak, American Walnut, and White Oak for authentic organic warmth.',
    properties: 'Natural grain grain patterns, 0.55mm slice thickness',
    durability: 'Exceptional with PU/Melamine protective seal',
    finish: 'Natural Matte, Open Pore PU, High Gloss Italian',
    usage: 'Living room feature walls, main door paneling, premium wardrobes',
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=600&q=80',
    isPublished: true,
  },
  {
    name: 'Anti-Fingerprint Acrylic & Matte Laminates',
    description: 'High-density European surface laminates with thermal healing properties and ultra-matte soft touch feeling.',
    properties: 'Zero reflection, scratch-resistant, anti-bacterial',
    durability: '15+ Years colourfastness',
    finish: 'Super Matte & Deep Gloss variations',
    usage: 'Modular kitchen shutters, wardrobe shutters, study tables',
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=600&q=80',
    isPublished: true,
  },
  {
    name: 'Solid Teak & Hardwood',
    description: 'Seasoned CP teakwood and Burma teak logs hand-selected for intricate CNC or hand-carved traditional wooden elements.',
    properties: 'High natural oil content, pest-resistant, dense grain',
    durability: 'Generational heirloom lifespan (50+ years)',
    finish: 'Hand-rubbed oil, wax finish, or poly-urethane lacquer',
    usage: 'Pooja room doors, solid dining tops, sofa framing, temple units',
    imageUrl: 'https://images.unsplash.com/photo-1549488344-cbb6c34cf08b?auto=format&fit=crop&w=600&q=80',
    isPublished: true,
  }
];

export const INITIAL_PROJECTS: Omit<Project, 'id'>[] = [
  {
    title: 'The Courtyard Villa — Luxury Residence',
    slug: 'the-courtyard-villa-luxury-residence',
    category: 'Living Hall',
    description: 'A complete interior architectural overhaul of a 3,800 sq.ft duplex in ECR Chennai, highlighting custom fluted walnut louvers, Italian marble TV framing, and warm ambient recessed lighting.',
    coverImage: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80'
    ],
    beforeImage: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1000&q=80',
    afterImage: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1000&q=80',
    materials: ['American Walnut Veneer', 'Italian Botticino Marble', 'Warm 2700K Architectural LEDs', 'BWP Marine Ply'],
    budget: '₹28 Lakhs',
    status: 'Completed',
    isPublished: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    title: 'Minimalist Modular Kitchen & Island',
    slug: 'minimalist-modular-kitchen-and-island',
    category: 'Kitchen',
    description: 'Modern handleless kitchen in Anna Nagar featuring dark charcoal acrylic shutters, quartz waterfall island, built-in pantry larder, and Blum motion Blumotion drawers.',
    coverImage: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1200&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=1000&q=80'
    ],
    beforeImage: 'https://images.unsplash.com/photo-1588854337221-4cf9fa96059c?auto=format&fit=crop&w=1000&q=80',
    afterImage: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1000&q=80',
    materials: ['Boiling Water Proof Ply', 'Matte Charcoal Acrylic', 'Silestone Quartz', 'Blum Tandembox'],
    budget: '₹9.5 Lakhs',
    status: 'Completed',
    isPublished: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    title: 'The Master Haven — Bespoke Suite',
    slug: 'the-master-haven-bespoke-suite',
    category: 'Bedroom',
    description: 'Warm, serene master suite with integrated champagne glass walk-in wardrobe, fluted headboard wall with acoustic felt lining, and custom teak vanity.',
    coverImage: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1200&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=80'
    ],
    materials: ['Fluted Teak Paneling', 'Anodized Champagne Glass', 'Suede Upholstery', 'Sensor Wardrobe Lighting'],
    budget: '₹14 Lakhs',
    status: 'Completed',
    isPublished: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    title: 'Adyar Executive Boardroom & Suites',
    slug: 'adyar-executive-boardroom-suites',
    category: 'Office',
    description: 'Modern corporate interior featuring custom 14-seater veneer boardroom table with hidden connectivity channels and sound-dampening wooden baffles.',
    coverImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1000&q=80'
    ],
    materials: ['Quarter Cut Teak Veneer', 'Acoustic Wood Paneling', 'Tempered Frosted Glass'],
    budget: '₹22 Lakhs',
    status: 'Completed',
    isPublished: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

export const INITIAL_GALLERY: Omit<GalleryItem, 'id'>[] = [
  {
    title: 'Handcrafted Fluted TV Console & Louver Wall',
    imageUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1000&q=80',
    category: 'Living Hall',
    description: 'Bespoke walnut paneling with hidden storage doors and indirect illumination.',
    isPublished: true,
    createdAt: new Date().toISOString(),
  },
  {
    title: 'Island Breakfast Bar with Soft Close Drawers',
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1000&q=80',
    category: 'Kitchen',
    description: 'Matte charcoal acrylic shutters with pure quartz worktop.',
    isPublished: true,
    createdAt: new Date().toISOString(),
  },
  {
    title: 'Floor-to-Ceiling Anodized Glass Wardrobe',
    imageUrl: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1000&q=80',
    category: 'Bedroom',
    description: 'Interior strip LED activation upon opening with velvet accessory organizers.',
    isPublished: true,
    createdAt: new Date().toISOString(),
  },
  {
    title: 'Carved Solid Teak Entrance Doorway',
    imageUrl: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1000&q=80',
    category: 'Other',
    description: 'Heavy CP teak wood with hand-polished polyurethane satin finish.',
    isPublished: true,
    createdAt: new Date().toISOString(),
  },
  {
    title: 'Contemporary Open Concept Dining Unit',
    imageUrl: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1000&q=80',
    category: 'Living Hall',
    description: 'Bar unit integrated with smoked glass display and brass metal inlays.',
    isPublished: true,
    createdAt: new Date().toISOString(),
  },
  {
    title: 'Executive Desk & Credenza in Adyar',
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1000&q=80',
    category: 'Office',
    description: 'Custom wire management system embedded inside natural teak desk.',
    isPublished: true,
    createdAt: new Date().toISOString(),
  }
];

export const INITIAL_REVIEWS: Omit<ReviewItem, 'id'>[] = [
  {
    customerName: 'Dr. Vignesh & Meenakshi',
    rating: 5,
    reviewText: 'K. Selvam sir and the JM INTERIOR team did phenomenal custom woodwork for our 4BHK apartment in Velachery. The precision in the modular kitchen and the teakwood pooja unit is breathtaking.',
    projectType: 'Full Home Interior',
    isPublished: true,
    createdAt: new Date().toISOString(),
  },
  {
    customerName: 'Anand Kumar',
    rating: 5,
    reviewText: 'Their joinery and woodwork quality is rare in Chennai today. Selvam brings genuine artisanal discipline. Delivered right on time with zero compromise on the marine ply specs.',
    projectType: 'Modular Kitchen & Living Space',
    isPublished: true,
    createdAt: new Date().toISOString(),
  },
  {
    customerName: 'Sangeetha Rangarajan',
    rating: 5,
    reviewText: 'The walk-in wardrobe with glass shutters and the master bedroom back wall panelling turned out exactly as we visualized. Honest pricing and outstanding craftsmanship.',
    projectType: 'Master Suite & Wardrobes',
    isPublished: true,
    createdAt: new Date().toISOString(),
  }
];
